### ISSUE TITLE
Default branch

### ISSUE THREAD

**Issue by shariq** [arpg/CVars#1]
Default branch should be master, not homebrew

**Comment by sinaaghli** [comment]
Hello,
As I can see default branch is master, what kind of issues you are having?

**Comment by crheckman** [comment]
I went ahead and changed it back to master this afternoon but did not reply, sorry about that. I believe the default branch may have been mistakenly set to homebrew but perhaps there was a reason I'm not aware of. Maybe @gsibley has a comment on that...

We will soon be merging homebrew into master to support installs so hopefully development downstream from CVars will respect the new format. Thanks for bringing this to our attention in the meantime!
