### ISSUE TITLE
Did you tested your code on Linux yourself?

### ISSUE THREAD

**Issue by memoryleakno1** [arpg/CVars#14]
I am actually trying to test your library and have run into multiple annoyances. I don't know if it is just me, but I have problems with your use of upper and lower case letters in file names and include directives.

When I cloned your code, I got folder "include/cvars" (all lowercase letters) with some includes in it. The thing is your code is refering to include dir as "CVars"  for example "CVars/CVar.h". That might work fine on windows which is case preserving but not case sensitive when it comes to file and directory names, but linux is case sensitive. I have to either fix all includes to be all lower case or rename folder from cvars  to CVars which I thought would be simpler fix, just to find that some of your includes are refering to "cvars/Cvars.h" as well! :-) 

I have finally just batch edited all references to be "cvars/filename.h" and changed all filenames to lowercase as well. I don't know if it was something on my part, but that's what I had to do to get your code to work.

**Comment by crheckman** [comment]
Hi there, thanks for your notes. Please submit a PR and we will be happy to
merge!

**Comment by memoryleakno1** [comment]
Here it is running on Arch with Compiz: http://imgur.com/a/FHMpn

I have done quite some ugly hacks. I had to hack your cvars/glplatform.h to include GL & GLUT on linux. It should be done in better way than what I did (just blatantly assumed that some flavour of glut is present). 

I was also not able to compile examples with your CMake files. Cmake worked to create shared library, but it couldn't find includes when compiling demos, and I personally hate CMake spaghetti, so instead of hacking CMake files I have used my own plain old Makefile to get demo2 to work. 

I haven't even try to boot into Windows and test if my changes break cmake build there (they shouldn't but without test one can't be sure). No idea if/how changes would affect anything/anyone else. But if you wan't changes I have no prolbmes with sharing them. I have just never done pull requests before, but I can test :).

**Comment by memoryleakno1** [comment]
Oh and btw, it will break CMake build on Linux since it will depends on old capitalized letters for files.

**Comment by memoryleakno1** [comment]
Ok, never mind CMake, I have edited original CMake that comes with project so it work fine now. Was able to compile everything including exampels with included CMake. 

May changes are now on github: https://github.com/memoryleakno1/CVars/tree/fixlinuxincludes

It's just a fast hack, decide for yourself if you want to include it in your code or not. 

Thanks for the project and best regards :-).

**Comment by crheckman** [comment]
@memoryleakno1 thanks for your help here. This should be solved by #17 (now merged into master). Please feel free to test yourself if you have the chance; remember to blow away your entire source directory when doing it since you're doing in-source builds and cmake meta files will be all over the place & may not update properly. Reopen if this is still broken.

**Comment by memoryleakno1** [comment]
Yeah, I saw comments and other commits. Actually it was blunder from me to rename headers and not just the directory; I realized it later, but didn't had time to fix it. Good if someone else fixed it. Will clone your master and try it again later this week. Best regards.
