### ISSUE TITLE
Tested master branch  a new today.

### ISSUE THREAD

**Issue by memoryleakno1** [arpg/CVars#19]
Examples were still referening to cvars with uppercase letters, as well as some other includes which made building on Linux to fail with missing files. Demo2 is using usleep which needs unistd.h header to be included. I have forked/cloned master branch a new, and fixed those thus new pull request. 

PS. 
There are no CMake build files in this one :-).

**Comment by crheckman** [comment]
We think we fixed this; please make a new issue if not!
