### ISSUE TITLE
CVars without GL dependency

### ISSUE THREAD

**Issue by dyerti** [arpg/CVars#9]
It would be nice if the default didn't force OpenGL and GLEW. TextConsole and console-less usage have no need for either.

It looks like the OpenGL and GLEW dependency can be optional.

Remove the REQUIRED from:
`find_package(OpenGL QUIET)`
`find_package(GLEW QUIET)`

Remove line from CVars.h:
`#include <CVars/glplatform.h>`

If you like I could submit a PR, but the changes are pretty minimal.

**Comment by gsibley** [comment]
Submit the PR and we'll merge.  Thanks!
